language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: EHlqkG7HsIYC4fLBZKHuFhgsctE/hLXKZ2BeCtnExVtB2WqMcE0YC2JNQDlU+pwl4rU8SqcGTa2QG5GBmkMR1H0g+9mCTY2Bol1kTMB95KxrWrGa85E1AnEoXIfGk5CmD4F4kP3DXRLgKErkpuQe4naHfFhVssbPJGl2hzPtVsFJuMg1zVZAH7dzDavLXY6p6exBef/tTAPaFsfXrfoBbwbByASL+m/pWzwwYpodJXeb8iH8l5vtnEWBQBKuD4hW4mMlpau7rYayq5C34FNIqtiCMvTJh9RutVDj2ENHiaPUNYCF3v7VGHqUiF/9eIKuMyq5mxP0CEShgEz7onYeP+JU30Ib6kUX89gugKetwux4Cu9MZ5VeBfiqGr3oryZTFPC953rRRqIm3RW3bmFLruiCwmyl6eSx0+qai+0Pu6BUW8NUcOYB6mYPCiQMSZ6GKTjxR8S5YNY5IrWMy0ypD0rgbvFv1aPiWMECLKDYsgJDkMCNVXq+QcgV3C/6ZwrL3zfuGOZdYVJIQbFum0UpfhkBTSfqnOylku1IzppnPS2lUcqo0gZ3F72temaIrfj1Npah3q0p0RVAJTvjdCKn1Vj1Bbf0+tYxB0XhzmFP/T2opG1aIM25z677E/WdkHTVx/C+QVEqJRlbWIkgqG+tWuadQIZVS9IhSkYpU5XdnJ8=
  app: fast-dusk-74105
  on:
    repo: briancbarrow/node-capstone
env:
  matrix:
    secure: GaP8DAB8tes+g6ms+WOXWW5fbGEEsJpepbul7pyF6FA91NravkFgOXV8wnJv4sAD3o3YgghKkiRovcKlphB6jlSQUv4SCUtTmEGeYWjWKuOW+/oa7B7pVO8b1kQfVpK9h8VZeqRR/MGKNeTwSWBPKvqgokeE7zR9NIdpu4OieFOZr2M/ii3fuynTfCEyg5SE9EokwGDPp7AzR6/28wW+EbmN1caszPasYbpHyENTWR9ulv9CJMTuLQp69svVSpgTa+GjdSh+3X5BTA02l6IBJD44DRtldWtgfnA9W4WaQld71Pn7t42bgdi4a5lWJpGZjIFNLW8w0l/3Ph86Yg2/GAZsGC8DTFnd1kj5wW8B+sjkpUzfona86wmFA1z4gLhSe1YwzwW8qOWYGp6Si93mgWRVDKNURvY8gukk1UfGbi39qRFIW/XKJCSMNEBnYbM3xe1CREtbpyZfX1Y6Qndi+cnz7TbAJ8qtsJ10JmgahKZKlf9kfjRdmWxkBUbsl3WkAMKO0k2Q+gnfM3+cdkftrXhY5zeSbjIXNOaUilDiFPOZ0S6c2cGjIFtzEc3cdNj6zZAjQYtKp8IAz/r+V8u0SFQcl6EqBXDa2GSjbwxVsO90/eILXWZtH0+SkuaF2s9ma9oNBypWyIq60CbNFK4Zq4Jc5WeY/ZjCT9FJmnTiqW8=
